version: "3.9"
services:
  database:
    image: mysql/mysql-server:5.6
    container_name: conference-event
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "event"